### ISSUE TITLE
Requesting clarification on how to use this repo.

### ISSUE THREAD

**Issue by wss-chadical** [ataylorme/Advanced-WordPress-on-Pantheon#117]
Readme is a bit vague on how to get this going.

Being an 'extension' of pantheon-systems/example-wordpress-composer does that imply that we do the initial setup stuff described in the example-wordpress-composer repo?
Such as terminus setup and exporting env vars for github/circleci.
But instead of:
terminus build:project:create pantheon-systems/example-wordpress-composer  my-new-site
Do this?:
terminus build:project:create ataylorme/Advanced-WordPress-on-Pantheon my-new-site

I'm going to go down the trial/error path here... 

Also, will this repo eventually be pulled under the patheon-systems org?

**Comment by wss-chadical** [comment]
"Edit .lando.yml and update name, site and id to match those of your Pantheon site"
A site that was already created? With an existing pantheon wordpress vanilla setup?

**Comment by ataylorme** [comment]
@wss-chadical `pantheon-systems/example-wordpress-composer` is meant to be a starting point and then customized to fit your needs.

This repository is an example of some customization (adding lighthouse, a gulp/sass build step, etc.).

This repository isn't meant to be used directly, more for learning purposes. It will not be owned by Pantheon at any point - it is my personal example.
