### ISSUE TITLE
Setting up WordHat correctly

### ISSUE THREAD

**Issue by tobeycodes** [ataylorme/Advanced-WordPress-on-Pantheon#32]
Although we require WordHat in our composer.json it has not been setup to use it. We should follow the [installation documentation](https://wordhat.info/installation/index.html)

**Comment by ataylorme** [comment]
@schrapel yup - this is a work in progress and I merged the initial branch for Behat testing to show an example of running a basic test. I plan on adding more examples (using WordHat).

**Comment by ataylorme** [comment]
A WordHat example is now included in `master`
