### ISSUE TITLE
Can not login in local machine

### ISSUE THREAD

**Issue by tannguyen04** [ataylorme/Advanced-WordPress-on-Pantheon#46]
I follow section "Local setup" and install successfully wordpress. But when I go to http://mysite.local/wp/wp-login.php it always redirect me to https://mysite.local/wp/wp-login.php and I can't login because my local machine not enable https.
I just commented line define( 'FORCE_SSL_ADMIN', true ); in web/wp-config.php and everything were worked.
My question is: I did wrong or right ? If wrong please correct me. If I commented line define( 'FORCE_SSL_ADMIN', true ) in web/wp-config.php, it will affect to pantheon site.

**Comment by tobeycodes** [comment]
That will be cached in your browser now.

I'd highly recommend using SSL locally if you use it on Pantheon for parity. Most local apps support them and personally I use Laravel Valet for this.

**Comment by ataylorme** [comment]
>  If I commented line `define( 'FORCE_SSL_ADMIN', true )` in `web/wp-config.php, it will affect to pantheon site.

You can wrap the check in a conditional so it only applies SSL to Pantheon

```
if ( isset( $_ENV['PANTHEON_ENVIRONMENT'] ) ){
    define( 'FORCE_SSL_ADMIN', true );
}
```
Though setting up SSL locally is preferred. +1 for [Laravel Valet](https://laravel.com/docs/5.4/valet). [Kalabox](http://www.kalabox.io/) also supports SSL and has even more parity to Pantheon.

Also make sure your `.env` file locally has the correct URL prefix (`http` or `https`).
