### ISSUE TITLE
Use `phpcs.xml.dist`

### ISSUE THREAD

**Issue by ataylorme** [ataylorme/Advanced-WordPress-on-Pantheon#57]
See comment in #50

> `phpcs.ruleset.xml`. My understanding would be ruleset would apply to something like WPCS or PSR and then we would bundle a file called `phpcs.xml.dist` . You could then drop the `--standard` as this would be looked at by default.

**Comment by tobeycodes** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file

Although we didn't name it `phpunit.xml.dist`. We should be consistent with whatever we do for phpunit and phpcs. I don't really understand the naming convention by adding `dist` to the end
