### ISSUE TITLE
Change VCS to be more flexible

### ISSUE THREAD

**Issue by RobWiddick** [ataylorme/Advanced-WordPress-on-Pantheon#65]
We'd like to be able to use Bitbucket instead of being forced to use Github. We know that if we provide a github key, even though we're using bitbucket, it will partially work. Pull requests from Bitbucket are numbered incorrectly on CircleCI causing issues.

I'm sure supporting other VCS's for deployment would be ideal as well. Perhaps an auto-detection method for popular VCS's.

**Comment by ataylorme** [comment]
@robertark work for this has been happening in the [Terminus build tools plugin](https://github.com/pantheon-systems/terminus-build-tools-plugin/https://github.com/pantheon-systems/terminus-build-tools-plugin/) which scaffolds a site from [example-wordpress-composer](https://github.com/pantheon-systems/example-wordpress-composer/).

Please test that plugin out with BitBucket and open an issue in that repo if you run intro problems. This repository of my own bash scripts paved the way for work in that plugin but a lot of the things I was doing manually are now incorporated into Terminus commands the plugin provides.
