### ISSUE TITLE
Cleaning up old multidevs fails

### ISSUE THREAD

**Issue by ataylorme** [ataylorme/Advanced-WordPress-on-Pantheon#66]
`[error]  Remote repository mismatch: local repository, git@github.com:ataylorme/Advanced-WordPress-on-Pantheon.git is different than the repository  associated with the site pantheon-wp-best-practices. `

See [build 514](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/514).

@greg-1-anderson any thoughts on how to fix this?

**Comment by greg-1-anderson** [comment]
Check the contents of your build-metadata.json file on the multidev being deleted. Your cwd should be at a local working copy of this same repository ('origin' should be the GitHub repository, not the Pantheon repository).

**Comment by ataylorme** [comment]
@greg-1-anderson I think I know what's going on. `build-meta.json` doesn't exist in the multidev being cleaned up as it's from before switching this repo over to build tools. I'll delete the multidevs manually.

**Comment by greg-1-anderson** [comment]
@stevector lobbied to make this command really conservative, so that it would be unlikely to ever "go rogue" and delete multidev environments that were not created by the build tools plugin.

Perhaps this error should just be a warning, so that it does not cause a test failure.

**Comment by ataylorme** [comment]
A warning makes sense so the builds don't fail but also might go unnoticed as people don't tend to look at the logs when things pass.
