### ISSUE TITLE
Build Stalled

### ISSUE THREAD

**Issue by nateluzod** [ataylorme/Advanced-WordPress-on-Pantheon#69]
In the `deploy_to_pantheon` step, my build is getting stuck here:

```
codeserver.dev.ffe57f82-7302-4@codeserver.dev.ffe57f82-7302-4c3a-b711-761ffc97e0e4.drush.in's password:
```

I've got the following environment variable set. Anything missing?

```
ADMIN_EMAIL
ADMIN_PASSWORD
GITHUB_TOKEN
GIT_EMAIL
TERMINUS_SITE
TERMINUS_TOKEN
TEST_SITE_NAME
```

**Comment by tobeycodes** [comment]
You need to create a ssh key. Then add the private key to circleci configuration in their web app and add the public key to Pantheon's dashboard.

**Comment by nateluzod** [comment]
@schrapel seems to be working now. Thanks!
