### ISSUE TITLE
Add yarn, instead of npm

### ISSUE THREAD

**Issue by ataylorme** [ataylorme/Advanced-WordPress-on-Pantheon#7]

**Comment by stevector** [comment]
Circle has yarn pre-installed on 14.04 but not 12.04 (which this repo is currently running) https://circleci.com/docs/install-and-use-yarn/

**Comment by ataylorme** [comment]
@stevector Yarn is useable with a higher version of node on the `12.04` image. I bumped the node version and did some other cleanup and Yarn is working now.

Thanks for kicking this off and the link to the doc.
